apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
spec:
  selector:
    app: scheduler
  ports:
    - protocol: TCP
      port: 8080  # The port you want to expose on the service
      targetPort: 8080  # The port your microservice listens on in the container
  type: LoadBalancer  # Use NodePort or ClusterIP as needed
