apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-scheduler-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: sms-scheduler
  template:
    metadata:
      labels:
        app: sms-scheduler
    spec:
      containers:
      - name: sms-scheduler
        image: sms-scheduler-image:latest
        # This field is used to specify when Kubernetes should pull images from a registry
        # For locally built images you don't need this field
        # image: your-docker-registry/scheduler-image:latest  # Replace with your image URL
        # imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        env:
          - name: RABBITMQ_URL
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_URL
        ports:
        - containerPort: 8080  # The port your Publisher service listens on
